//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Convier
    {
        public int IdEvenement { get; set; }
        public int IdCategorieVIP { get; set; }
        public string Message { get; set; }
    
        public virtual CategorieVIP CategorieVIP { get; set; }
        public virtual Evenement Evenement { get; set; }
    }
}
