//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evenement
    {
        public int Id { get; set; }
        public System.DateTime DateDebut { get; set; }
        public System.DateTime DateFin { get; set; }
        public string Intitule { get; set; }
        public int IdTheme { get; set; }
        public string CodeInseeVille { get; set; }
        public int IdCategorieVIP { get; set; }
        public int IdCampagne { get; set; }
    
        public virtual Campagne Campagne { get; set; }
        public virtual CategorieVIP CategorieVIP { get; set; }
        public virtual Convier Convier { get; set; }
        public virtual Ville Ville { get; set; }
        public virtual Theme Theme { get; set; }
        public virtual Participer Participer { get; set; }
    }
}
