//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GsbCampagneDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIP
    {
        public int Id { get; set; }
        public string Nom { get; set; }
        public string AdressePostal { get; set; }
        public string Email { get; set; }
        public int IdCategorieVIP { get; set; }
        public string CodeInseeVille { get; set; }
    
        public virtual CategorieVIP CategorieVIP { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
